//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Assets/Scripts/Gameplay/ChatboxUI.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Assets/Scripts/Gameplay/ChatboxUI.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ChatUI: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ChatUI()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ChatboxUI"",
    ""maps"": [
        {
            ""name"": ""ChatboxUI"",
            ""id"": ""41c210d0-26d9-48ac-b595-99e249b4e663"",
            ""actions"": [
                {
                    ""name"": ""CloseChat"",
                    ""type"": ""Button"",
                    ""id"": ""fc0ad060-80b5-46b9-8bbd-08c82add2163"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SendMessage"",
                    ""type"": ""Button"",
                    ""id"": ""cf905480-3ac5-4c00-a146-b2789c82ba4b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""447581f6-79fd-4807-837a-576ce8995e23"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseChat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63829098-13d3-46cf-8c5e-2d1a52dd173a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SendMessage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32998c00-ce43-45ac-b168-4f7ec6b5dc00"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SendMessage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ChatboxUI
        m_ChatboxUI = asset.FindActionMap("ChatboxUI", throwIfNotFound: true);
        m_ChatboxUI_CloseChat = m_ChatboxUI.FindAction("CloseChat", throwIfNotFound: true);
        m_ChatboxUI_SendMessage = m_ChatboxUI.FindAction("SendMessage", throwIfNotFound: true);
    }

    ~@ChatUI()
    {
        UnityEngine.Debug.Assert(!m_ChatboxUI.enabled, "This will cause a leak and performance issues, ChatUI.ChatboxUI.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ChatboxUI
    private readonly InputActionMap m_ChatboxUI;
    private List<IChatboxUIActions> m_ChatboxUIActionsCallbackInterfaces = new List<IChatboxUIActions>();
    private readonly InputAction m_ChatboxUI_CloseChat;
    private readonly InputAction m_ChatboxUI_SendMessage;
    /// <summary>
    /// Provides access to input actions defined in input action map "ChatboxUI".
    /// </summary>
    public struct ChatboxUIActions
    {
        private @ChatUI m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ChatboxUIActions(@ChatUI wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ChatboxUI/CloseChat".
        /// </summary>
        public InputAction @CloseChat => m_Wrapper.m_ChatboxUI_CloseChat;
        /// <summary>
        /// Provides access to the underlying input action "ChatboxUI/SendMessage".
        /// </summary>
        public InputAction @SendMessage => m_Wrapper.m_ChatboxUI_SendMessage;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ChatboxUI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ChatboxUIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ChatboxUIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ChatboxUIActions" />
        public void AddCallbacks(IChatboxUIActions instance)
        {
            if (instance == null || m_Wrapper.m_ChatboxUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ChatboxUIActionsCallbackInterfaces.Add(instance);
            @CloseChat.started += instance.OnCloseChat;
            @CloseChat.performed += instance.OnCloseChat;
            @CloseChat.canceled += instance.OnCloseChat;
            @SendMessage.started += instance.OnSendMessage;
            @SendMessage.performed += instance.OnSendMessage;
            @SendMessage.canceled += instance.OnSendMessage;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ChatboxUIActions" />
        private void UnregisterCallbacks(IChatboxUIActions instance)
        {
            @CloseChat.started -= instance.OnCloseChat;
            @CloseChat.performed -= instance.OnCloseChat;
            @CloseChat.canceled -= instance.OnCloseChat;
            @SendMessage.started -= instance.OnSendMessage;
            @SendMessage.performed -= instance.OnSendMessage;
            @SendMessage.canceled -= instance.OnSendMessage;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ChatboxUIActions.UnregisterCallbacks(IChatboxUIActions)" />.
        /// </summary>
        /// <seealso cref="ChatboxUIActions.UnregisterCallbacks(IChatboxUIActions)" />
        public void RemoveCallbacks(IChatboxUIActions instance)
        {
            if (m_Wrapper.m_ChatboxUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ChatboxUIActions.AddCallbacks(IChatboxUIActions)" />
        /// <seealso cref="ChatboxUIActions.RemoveCallbacks(IChatboxUIActions)" />
        /// <seealso cref="ChatboxUIActions.UnregisterCallbacks(IChatboxUIActions)" />
        public void SetCallbacks(IChatboxUIActions instance)
        {
            foreach (var item in m_Wrapper.m_ChatboxUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ChatboxUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ChatboxUIActions" /> instance referencing this action map.
    /// </summary>
    public ChatboxUIActions @ChatboxUI => new ChatboxUIActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ChatboxUI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ChatboxUIActions.AddCallbacks(IChatboxUIActions)" />
    /// <seealso cref="ChatboxUIActions.RemoveCallbacks(IChatboxUIActions)" />
    public interface IChatboxUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "CloseChat" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCloseChat(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SendMessage" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSendMessage(InputAction.CallbackContext context);
    }
}
